import { useState } from "react";

function AuditTrail() {
  const [filter, setFilter] = useState("All");

  const auditLogs = [
    {
      id: 1,
      action: "AI Match Generated",
      material: "SS Ball Valve 2 Inch",
      materialCode: "CPCL-VAL-1023",
      user: "AI Matching Engine",
      time: "Today, 10:42 AM",
      status: "AI Generated",
    },
    {
      id: 2,
      action: "Mapping Approved",
      material: "Stainless Steel Ball Valve",
      materialCode: "NMC-VAL-0001",
      user: "Material Validation Officer",
      time: "Today, 10:55 AM",
      status: "Approved",
    },
    {
      id: 3,
      action: "National Code Generated",
      material: "Copper Electrical Cable",
      materialCode: "NMC-ELE-0002",
      user: "National Material Admin",
      time: "Today, 11:10 AM",
      status: "Generated",
    },
    {
      id: 4,
      action: "Material Mapping Rejected",
      material: "Industrial Pump Assembly",
      materialCode: "BHEL-PMP-220",
      user: "Technical Reviewer",
      time: "Yesterday, 4:30 PM",
      status: "Rejected",
    },
    {
      id: 5,
      action: "Material Record Updated",
      material: "Copper Cable 10 Sqmm",
      materialCode: "ONGC-CAB-3321",
      user: "Data Administrator",
      time: "Yesterday, 2:15 PM",
      status: "Updated",
    },
  ];

  const filteredLogs =
    filter === "All"
      ? auditLogs
      : auditLogs.filter((log) => log.status === filter);

  return (
    <div className="audit-page">
      <div className="page-header">
        <div>
          <h1>Audit Trail & Governance</h1>

          <p>
            Track AI recommendations, validation decisions, material mappings,
            national code generation and changes across the platform.
          </p>
        </div>
      </div>

      {/* GOVERNANCE SUMMARY */}

      <div className="governance-grid">
        <div className="governance-card">
          <span>Total Activities</span>
          <h2>{auditLogs.length}</h2>
          <p>Recorded system events</p>
        </div>

        <div className="governance-card">
          <span>Approved Actions</span>
          <h2>
            {
              auditLogs.filter(
                (log) => log.status === "Approved"
              ).length
            }
          </h2>
          <p>Validated material mappings</p>
        </div>

        <div className="governance-card">
          <span>AI Recommendations</span>
          <h2>
            {
              auditLogs.filter(
                (log) => log.status === "AI Generated"
              ).length
            }
          </h2>
          <p>Generated by AI engine</p>
        </div>

        <div className="governance-card">
          <span>Rejected Actions</span>
          <h2>
            {
              auditLogs.filter(
                (log) => log.status === "Rejected"
              ).length
            }
          </h2>
          <p>Rejected during validation</p>
        </div>
      </div>

      {/* FILTERS */}

      <div className="audit-controls">
        <div>
          <h2>Activity History</h2>
          <p>Complete record of material master activities.</p>
        </div>

        <select
          value={filter}
          onChange={(e) => setFilter(e.target.value)}
          className="audit-filter"
        >
          <option value="All">All Activities</option>
          <option value="AI Generated">AI Generated</option>
          <option value="Approved">Approved</option>
          <option value="Generated">Code Generated</option>
          <option value="Rejected">Rejected</option>
          <option value="Updated">Updated</option>
        </select>
      </div>

      {/* AUDIT LOGS */}

      <div className="audit-log-container">
        {filteredLogs.length > 0 ? (
          filteredLogs.map((log) => (
            <div className="audit-log" key={log.id}>
              <div className="audit-icon">
                {log.status === "Approved" && "✓"}
                {log.status === "Rejected" && "✕"}
                {log.status === "AI Generated" && "AI"}
                {log.status === "Generated" && "#"}
                {log.status === "Updated" && "↻"}
              </div>

              <div className="audit-details">
                <h3>{log.action}</h3>

                <p>
                  <strong>{log.material}</strong>
                  {" • "}
                  {log.materialCode}
                </p>

                <span>
                  By {log.user} · {log.time}
                </span>
              </div>

              <span
                className={`audit-status ${log.status
                  .toLowerCase()
                  .replace(" ", "-")}`}
              >
                {log.status}
              </span>
            </div>
          ))
        ) : (
          <div className="no-logs">
            <h3>No activities found</h3>
            <p>Try selecting a different filter.</p>
          </div>
        )}
      </div>
    </div>
  );
}

export default AuditTrail;